Blog/accounts/urls.py
from django.urls import path
from .views import RegisterView

app_name = 'accounts'
urlpatterns = [
path('signup/', RegisterView.as_view(), name='signup'),
]

Blog/blog/urls.py
from django.urls import path
from .views import (BlogListView, BlogDetailView, 
                    BlogCreateView, BlogUpdateView, BlogDeleteView, BlogCommentView)

app_name = 'blog'

urlpatterns = [
path('', BlogListView.as_view(), name='home'),
path('post/<int:pk>/', BlogDetailView.as_view(), name='detail'),
path('post/new/', BlogCreateView.as_view(), name='new_post'),
path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='edit_post'),
path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='delete_post'),
path('post/<int:pk>/comment/', BlogCommentView.as_view(), name='add_comment'),
]

Blog/crud/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
path('admin/', admin.site.urls),
path('', include('blog.urls', namespace='blog')), 
path('accounts/', include('django.contrib.auth.urls')), 
path('accounts/', include('accounts.urls', namespace='accounts')),
]

Blog/accounts/models.py
from django.db import models

# Create your models here.

Blog/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

class Post(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    body = models.TextField()
    
    def __str__(self):
        return self.title

    def get_absolute_url(self): 
        return reverse('blog:detail', args=[str(self.id)])

class Comment(models.Model):
    blog = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE,
        related_name='comments'
        )
    date_added = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=140)
    
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('blog:home')

Blog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', )

Blog/accounts/views.py
from .forms import RegistrationForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.contrib import messages

from django.views import View

class RegisterView(View):
    def get(self, request):
        return render(request, 'registration/signup.html', { 'register_form': RegistrationForm() })
    
    def post(self, request):
        context = {}
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            context['message'] = 'Registration Successful'
            
            # return redirect(reverse('login'))
        context['register_form'] = form
        return render(request, 'registration/signup.html', context)

Blog/blog/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Comment, Post
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'posts'
    queryset = Post.objects.all().order_by('-id')

class BlogDetailView(DetailView): 
    model = Post
    template_name = 'detail.html'
    context_object_name = 'post'
    http_method_names = ['get']

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'new_post.html'
    fields = ['title', 'body']
    success_url = "/"

    def form_valid(self, form): 
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView): 
    model = Post
    template_name = 'edit_post.html'
    fields = ['title', 'body']

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('blog:home')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class BlogCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'add_comment.html'
    fields = ['comment']
    success_url = "/"

    def form_valid(self, form): 
        form.instance.blog_id = self.kwargs['pk']
        form.instance.author = self.request.user
        return super().form_valid(form)

    

Blog/templates/add_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title %}Add Comment to {{post.title}}{% endblock %}
{% block content %}
    <h1 class="mt-2 text-success">Add Comment</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Save">
    </form>
{% endblock content %}

Blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{%block title %}Base Page{% endblock %} </title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="styleshee\
        t">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
            crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
    
        
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Tech Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav d-flex ml-auto">
                        <a href="{% url 'blog:new_post' %}" class="btn btn-primary mr-auto py-1 px-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
                            </svg>
                            New
                        </a>
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#"
                                id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-lg-right"
                                aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'password_change' %}">
                                    Change password
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    Log Out
                                </a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'login' %}" class="btn btn-primary">
                        Log In
                    </a>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">
                        Sign up
                    </a>
                </form>
                {% endif %}
            </div>
        </nav>
        <main>
            <style type="text/css">
                .main{
                    min-height: 100vh;
                    height: 100%;
                }
            </style>
            <div class="main container">
                {% block content %}
            
                {% endblock content %}
            </div>
        </main>

        <footer>
            <style type="text/css">
                .footer{
                    min-height: 100px;
                }
            </style>
            
            <br>
            <div class="d-flex flex-row align-items-center footer  bg-white border-top shadow-lg">
                <p class="m-auto">Designed by Miracle Iloh | 2021</p>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    </body>
</html>

Blog/templates/delete_post.html
{% extends 'base.html' %}
{%block title %}Delete Post{% endblock %}

{% block content %}
    <h1 class="mt-2">Delete post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input class="btn btn-danger" type="submit" value="Confirm">
        <button class="btn btn-warning active text-white"><a href="{% url 'blog:home' %}">Cancel</a></button>
    </form>
{% endblock content %}

Blog/templates/detail.html
{% extends 'base.html' %}

{%block title %}Post Details{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-2">
                <div class="post-entry">
                    <h2 class="text-primary">{{ post.title }}</h2>
                    <p>{{ post.body }}</p>
                    <div class="card-footer text-center text-muted mt-4">
                        {% if post.author == request.user %}
                            <a href="{%url 'blog:edit_post' post.pk %}">Edit</a> | <a href="{%url 'blog:delete_post' post.pk%}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Blog/templates/edit_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title %}Edit Post{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-2">
            <h1 class="mt-2 text-info">Edit post</h1>
            <form class="container-sm" action="" method="post">{% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-info" type="submit">Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Blog/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    {% for post in posts %}

    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold">{{ post.title }}</span> &middot;
            <span class="text-muted">by {{ post.author }} |
        {{ post.date }}</span>
        </div>
        <div class="card-body">
            {{ post.body }}
            {% if user.is_authenticated %}
                <a href="{%url 'blog:detail' post.pk%}">details</a>
            {% endif %}
        </div>
        <div class="card-footer">
            <div>
                {% if not post.comments.all %}
                    <strong class="mr-4 text-info">No Comments Yet...</strong><a href="{% url 'blog:add_comment' post.pk%}">Add One</a>
                {% else %}
                    <strong class="mr-4 text-info">Comments...</strong>
                    {% for comment in post.comments.all %}
                        <p>
                            <span class="font-weight-bold">
                                {{ comment.author }} | {{ comment.date_added }} 
                                <!-- |date:'F j, Y, g:i a'  -->
                            </span>
                            {{ comment }}
                        </p>
                    {% endfor %}
                    <a href="{% url 'blog:add_comment' post.pk %}">Add More</a> 
                {% endif %}
            </div>
        </div>
        
    </div>
    <br />

    {% endfor %}
{% endblock content %}

Blog/templates/new_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title %}New Post{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-2">
                <h1 class="mt-2 text-primary">New post</h1>
                <form action="" method="post">{% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}